### ISSUE TITLE
this player is based on an old version of jPlayer

### ISSUE THREAD

**Issue by veloopity** [BeyondHyper/responsive-jPlayer#5]
the whitenoise player that I use seems to be based on jPlayer 2.6.4 which has various issues (e.g. on Android devices). Someone from the jPlayer google group told me I should update to jPlayer 2.9 but I have no idea how to do that as the jPlayer code seems mixed with whitenoise code - can you do it?

-Michael

**Comment by veloopity** [comment]
hello? anyone listening?

**Comment by derick-montague** [comment]
Hey Michael,

Sorry, I wasn't and I am going to be making many changes to this repo over the next few weeks. Thank you for logging the issue!

Derick
